from _typeshed import Incomplete
from onepassword.desktop_core import DesktopCore as DesktopCore
from onepassword.errors import DesktopSessionExpiredException as DesktopSessionExpiredException, raise_typed_exception as raise_typed_exception
from typing import Any, Protocol

MESSAGE_LIMIT: Incomplete

class Core(Protocol):
    async def init_client(self, client_config: dict) -> str: ...
    async def invoke(self, invoke_config: dict) -> str: ...
    def invoke_sync(self, invoke_config: dict) -> str: ...
    def release_client(self, client_id: int) -> None: ...

class InnerClient:
    client_id: int
    core: DesktopCore | UniffiCore
    config: dict[str, Any]
    def __init__(self, client_id: int, core: DesktopCore | UniffiCore, config: dict[str, any]) -> None: ...
    async def invoke(self, invoke_config: dict): ...

class UniffiCore:
    core: Incomplete
    def __init__(self) -> None: ...
    async def init_client(self, client_config: dict): ...
    async def invoke(self, invoke_config: dict): ...
    def invoke_sync(self, invoke_config: dict): ...
    def release_client(self, client_id: int): ...
