from _typeshed import Incomplete
from onepassword.errors import raise_typed_exception as raise_typed_exception

def find_1password_lib_path(): ...

class DesktopCore:
    lib: Incomplete
    account_name: Incomplete
    send_message: Incomplete
    free_message: Incomplete
    def __init__(self, account_name: str) -> None: ...
    def call_shared_library(self, payload: str, operation_kind: str) -> bytes: ...
    async def init_client(self, config: dict) -> int: ...
    async def invoke(self, invoke_config: dict) -> str: ...
    def release_client(self, client_id: int): ...

ERR_CHANNEL_CLOSED: str
ERR_CONNECTION_DROPPED: str
ERR_INTERNAL_FMT: str

def error_from_return_code(ret_code: int) -> Exception | None: ...
