from .core import InnerClient as InnerClient
from .types import DocumentCreateParams as DocumentCreateParams, FileAttributes as FileAttributes, FileCreateParams as FileCreateParams, Item as Item
from _typeshed import Incomplete

class ItemsFiles:
    inner_client: Incomplete
    def __init__(self, inner_client: InnerClient) -> None: ...
    async def attach(self, item: Item, file_params: FileCreateParams) -> Item: ...
    async def read(self, vault_id: str, item_id: str, attr: FileAttributes) -> bytes: ...
    async def delete(self, item: Item, section_id: str, field_id: str) -> Item: ...
    async def replace_document(self, item: Item, doc_params: DocumentCreateParams) -> Item: ...
