from .core import InnerClient as InnerClient
from .items_files import ItemsFiles as ItemsFiles
from .items_shares import ItemsShares as ItemsShares
from .types import Item as Item, ItemCreateParams as ItemCreateParams, ItemListFilter as ItemListFilter, ItemOverview as ItemOverview, ItemsDeleteAllResponse as ItemsDeleteAllResponse, ItemsGetAllResponse as ItemsGetAllResponse, ItemsUpdateAllResponse as ItemsUpdateAllResponse
from _typeshed import Incomplete

class Items:
    inner_client: Incomplete
    shares: Incomplete
    files: Incomplete
    def __init__(self, inner_client: InnerClient) -> None: ...
    async def create(self, params: ItemCreateParams) -> Item: ...
    async def create_all(self, vault_id: str, params: list[ItemCreateParams]) -> ItemsUpdateAllResponse: ...
    async def get(self, vault_id: str, item_id: str) -> Item: ...
    async def get_all(self, vault_id: str, item_ids: list[str]) -> ItemsGetAllResponse: ...
    async def put(self, item: Item) -> Item: ...
    async def delete(self, vault_id: str, item_id: str) -> None: ...
    async def delete_all(self, vault_id: str, item_ids: list[str]) -> ItemsDeleteAllResponse: ...
    async def archive(self, vault_id: str, item_id: str) -> None: ...
    async def list(self, vault_id: str, *filters: ItemListFilter) -> list[ItemOverview]: ...
