from .core import InnerClient as InnerClient
from .types import Item as Item, ItemShareAccountPolicy as ItemShareAccountPolicy, ItemShareParams as ItemShareParams, ValidRecipient as ValidRecipient
from _typeshed import Incomplete

class ItemsShares:
    inner_client: Incomplete
    def __init__(self, inner_client: InnerClient) -> None: ...
    async def get_account_policy(self, vault_id: str, item_id: str) -> ItemShareAccountPolicy: ...
    async def validate_recipients(self, policy: ItemShareAccountPolicy, recipients: list[str]) -> list[ValidRecipient]: ...
    async def create(self, item: Item, policy: ItemShareAccountPolicy, params: ItemShareParams) -> str: ...
