from .core import InnerClient as InnerClient, UniffiCore as UniffiCore
from .types import GeneratePasswordResponse as GeneratePasswordResponse, PasswordRecipe as PasswordRecipe, ResolveAllResponse as ResolveAllResponse
from _typeshed import Incomplete

class Secrets:
    inner_client: Incomplete
    def __init__(self, inner_client: InnerClient) -> None: ...
    async def resolve(self, secret_reference: str) -> str: ...
    async def resolve_all(self, secret_references: list[str]) -> ResolveAllResponse: ...
    @staticmethod
    def validate_secret_reference(secret_reference: str) -> None: ...
    @staticmethod
    def generate_password(recipe: PasswordRecipe) -> GeneratePasswordResponse: ...
