from .core import InnerClient as InnerClient
from .types import GroupAccess as GroupAccess, GroupVaultAccess as GroupVaultAccess, Vault as Vault, VaultCreateParams as VaultCreateParams, VaultGetParams as VaultGetParams, VaultListParams as VaultListParams, VaultOverview as VaultOverview, VaultUpdateParams as VaultUpdateParams
from _typeshed import Incomplete

class Vaults:
    inner_client: Incomplete
    def __init__(self, inner_client: InnerClient) -> None: ...
    async def create(self, params: VaultCreateParams) -> Vault: ...
    async def list(self, params: VaultListParams | None = None) -> list[VaultOverview]: ...
    async def get_overview(self, vault_id: str) -> VaultOverview: ...
    async def get(self, vault_id: str, vault_params: VaultGetParams) -> Vault: ...
    async def update(self, vault_id: str, params: VaultUpdateParams) -> Vault: ...
    async def delete(self, vault_id: str) -> None: ...
    async def grant_group_permissions(self, vault_id: str, group_permissions_list: list[GroupAccess]) -> None: ...
    async def update_group_permissions(self, group_permissions_list: list[GroupVaultAccess]) -> None: ...
    async def revoke_group_permissions(self, vault_id: str, group_id: str) -> None: ...
